# you can remove this file if you don't need to express dependencies, else
# add dependent roles as a list to the `dependencies` section. Filling the rest is optional.
galaxy_info:
  author: Bilhan Kara√∂ren, Ali Akkaya
  description: This role converts RHV disks between raw and cow formats
  role_name: vm_disk_convert
  company: Red Hat, Inc.

  license: CC-BY-SA-4.0

  min_ansible_version: 2.9

  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
    - ovirtdisk
    - convert
    - rhv

dependencies:
  - ovirt.ovirt
